StimulateOpenGL_II: GLWindow Class Reference
GLWindow Class Reference
The main Open GL display window.
#include <GLWindow.h>
Public Slots
void pauseUnpause ()
Toggles the paused/unpaused state of the plugin execution engine.
Public Member Functions
~GLWindow ()
StimPlugin * pluginFind (const QString &name, bool casesensitive=false)
Find a plugin by name. Returns a pointer to the plugin if found, or NULL if not found.
StimPlugin * runningPlugin () const
bool isPaused () const
Returns true if plugin execution is in the paused state, false otherwise.
QList< QString > plugins () const
Returns a list of all the plugin names that are currently loaded (but not necessarily running).
Protected Member Functions
void pluginCreated (StimPlugin *plugin)
Plugins call this when they want to tell the execution engine that they have been created.
void pluginStarted (StimPlugin *plugin)
Plugins call this method when they want to tell the execution engine that they have been started.
void pluginStopped (StimPlugin *plugin)
Plugins call this method when they want to tell the execution engine that they have been stopped.
void pluginDeleted (StimPlugin *plugin)
Plugins call this method to inform the execution engine that they are being deleted and should be dereferenced from any internal data structures.
void initializeGL ()
Sets up the rendering context, clears the screen, sets/unsets various opengl parameters.
void resizeGL (int w, int h)
Sets up the viewport and projection etc.:.
void paintGL ()
Called once per vblank to draw each frame.
void closeEvent (QCloseEvent *event)
override close events -- prevent window from being closed!
void resizeEvent (QResizeEvent *event)
overrides QWidget method -- prevent window resize
void keyPressEvent (QKeyEvent *event)
overrides QWidget methoed -- catch keypresses -- all keyboard handling happens in this class
Friends
class StimPlugin
class StimApp
Detailed Description
The main Open GL display window.
This class encapsulates the main OpenGL window that the application uses to render graphics to.
It also manages plugins and plugin execution via the pluginFind(), runningPlugin(), isPaused() and plugins() methods.
This class also handles all keyboard hotkeys (see keyPressEvent())
Definition at line 22 of file GLWindow.h.
Constructor & Destructor Documentation
GLWindow::~GLWindow ()
Definition at line 49 of file GLWindow.cpp.
References StimPlugin::stop().
Member Function Documentation
StimPlugin * GLWindow::pluginFind (const QString & name, bool casesensitive = false)
Find a plugin by name. Returns a pointer to the plugin if found, or NULL if not found.
Definition at line 226 of file GLWindow.cpp.
Referenced by ConnectionThread::eventFilter(), and StimApp::loadStim().
StimPlugin* GLWindow::runningPlugin () const [inline]
The currently running plugin, if any. Returns NULL if no plugin is running.
Definition at line 39 of file GLWindow.h.
Referenced by ConnectionThread::eventFilter(), StimPlugin::getFrameDump(), StimApp::loadStim(), and StimPlugin::~StimPlugin().
bool GLWindow::isPaused () const [inline]
Returns true if plugin execution is in the paused state, false otherwise.
Definition at line 41 of file GLWindow.h.
Referenced by StimPlugin::getFrameDump().
QList< QString > GLWindow::plugins () const
Returns a list of all the plugin names that are currently loaded (but not necessarily running).
Definition at line 318 of file GLWindow.cpp.
void GLWindow::pauseUnpause () [slot]
Toggles the paused/unpaused state of the plugin execution engine.
Definition at line 309 of file GLWindow.cpp.
References StimPlugin::frameNum, StimPlugin::needNotifyStart, and StimPlugin::notifySpikeGLAboutStart().
Referenced by StimPlugin::start().
void GLWindow::pluginCreated (StimPlugin * plugin) [protected]
Plugins call this when they want to tell the execution engine that they have been created.
Definition at line 192 of file GLWindow.cpp.
Referenced by StimPlugin::StimPlugin().
void GLWindow::pluginStarted (StimPlugin * plugin) [protected]
Plugins call this method when they want to tell the execution engine that they have been started.
Definition at line 205 of file GLWindow.cpp.
References StimPlugin::name(), and StimPlugin::stop().
Referenced by StimPlugin::start().
void GLWindow::pluginStopped (StimPlugin * plugin) [protected]
Plugins call this method when they want to tell the execution engine that they have been stopped.
Definition at line 213 of file GLWindow.cpp.
References StimPlugin::name(), and WINDOW_TITLE.
Referenced by StimPlugin::stop().
void GLWindow::pluginDeleted (StimPlugin * plugin) [protected]
Plugins call this method to inform the execution engine that they are being deleted and should be dereferenced from any internal data structures.
Definition at line 199 of file GLWindow.cpp.
Referenced by StimPlugin::~StimPlugin().
void GLWindow::initializeGL () [protected]
Sets up the rendering context, clears the screen, sets/unsets various opengl parameters.
Definition at line 79 of file GLWindow.cpp.
void GLWindow::resizeGL (int w, int h) [protected]
Sets up the viewport and projection etc.:.
Definition at line 97 of file GLWindow.cpp.
void GLWindow::paintGL () [protected]
Called once per vblank to draw each frame.
Updates some statistics, then calls the currently active plugin's StimPlugin::drawFrame() virtual function. Note that if no plugin is running or if plugin execution is paused the plugin's drawFrame() function is not called.
Definition at line 110 of file GLWindow.cpp.
References StimPlugin::afterVSync(), StimPlugin::computeFPS(), StimPlugin::cycleTimeLeft, StimPlugin::drawFrame(), StimPlugin::frameNum, Util::getHWFrameCount(), Util::getHWRefreshRate(), Util::getNProcessors(), Util::getTime(), Util::hasAccurateHWFrameCount(), StimPlugin::putMissedFrame(), StimApp::refreshRate(), and Util::stimApp().
void GLWindow::closeEvent (QCloseEvent * event) [protected]
override close events -- prevent window from being closed!
Definition at line 56 of file GLWindow.cpp.
References Util::stimApp().
void GLWindow::resizeEvent (QResizeEvent * event) [protected]
overrides QWidget method -- prevent window resize
Definition at line 67 of file GLWindow.cpp.
void GLWindow::keyPressEvent (QKeyEvent * event) [protected]
overrides QWidget methoed -- catch keypresses -- all keyboard handling happens in this class
Definition at line 264 of file GLWindow.cpp.
References StimApp::hideUnhideConsole(), StimApp::pauseUnpause(), StimPlugin::processKey(), StimApp::setDebugMode(), and Util::stimApp().
Friends And Related Function Documentation
friend class StimPlugin [friend]
Definition at line 26 of file GLWindow.h.
friend class StimApp [friend]
Definition at line 27 of file GLWindow.h.
The documentation for this class was generated from the following files:
GLWindow.h
GLWindow.cpp