StimulateOpenGL_II: MovingGrating Class Reference
MovingGrating Class Reference
A plugin that draws a moving 'grating' or set of bars.
#include <MovingGrating.h>
Protected Member Functions
MovingGrating ()
can only be constructed by our friend class
void drawFrame ()
The meat of every plugin -- re-implement this function to draw the actual frame. Class variable frameNum holds the frame number.
bool init ()
Called as a result of start() when plugin is started.
Friends
class GLWindow
Detailed Description
A plugin that draws a moving 'grating' or set of bars.
This plugin basically draws a moving grating in the GLWindow. The grating appears as a set of parallel bars with a periodic intensity.
The grating is rotated at whatever angle the user specifies.
It also moves across the screen from right to left at whatever speed the user specifies.
For a full description of this plugin's parameters, it is recommended you see the Plugin Parameter Documentation for more details.
Definition at line 19 of file MovingGrating.h.
Constructor & Destructor Documentation
MovingGrating::MovingGrating () [protected]
can only be constructed by our friend class
Definition at line 4 of file MovingGrating.cpp.
Member Function Documentation
void MovingGrating::drawFrame () [protected, virtual]
The meat of every plugin -- re-implement this function to draw the actual frame. Class variable frameNum holds the frame number.
Implements StimPlugin.
Definition at line 27 of file MovingGrating.cpp.
References GridPlugin::drawGrid(), and GridPlugin::setGrayLevel().
bool MovingGrating::init () [protected, virtual]
Called as a result of start() when plugin is started.
You should reimplement this in your plugin to add initialization code for class variables, etc. It's important to properly initialize all variables that affect your drawFrame() function so that subsequent runs of the same plugin are identical and not polluted by crufty old state variables. Default implementation does nothing. Return false if you want to indicate init failure for some reason.
Reimplemented from StimPlugin.
Definition at line 9 of file MovingGrating.cpp.
References StimPlugin::getParam(), and GridPlugin::setupGrid().
Friends And Related Function Documentation
friend class GLWindow [friend]
Reimplemented from StimPlugin.
Definition at line 25 of file MovingGrating.h.
The documentation for this class was generated from the following files:
MovingGrating.h
MovingGrating.cpp