StimulateOpenGL_II: StimParams Class Reference
StimParams Class Reference
Encapsulates the parameters for a StimPlugin.
#include <StimParams.h>
Public Member Functions
StimParams ()
StimParams (const QString &str)
void fromString (const QString &)
Parses an ini-stile string to set the params.
QString toString () const
bool fromFile (const QString &file)
Reads the entire contents of file into memory as a QString then calls fromString() on this string.
Detailed Description
Encapsulates the parameters for a StimPlugin.
An association of name/value pairs. The names are strings and the values are a QVariant (float, int, string, etc -- anything QVariant supports).
Use the toString() method to generate a config-file style string (suitable to pass to matlab clients or to save as a config file).
The fromString() function parses parameters.
Format for the string that the toString() and fromString() functions use is
   name1 = value1
   name2 = value2
   ...etc...
(this is much like the configuration file format for the original StimulateOpenGL)
Definition at line 27 of file StimParams.h.
Constructor & Destructor Documentation
StimParams::StimParams () [inline]
Definition at line 30 of file StimParams.h.
StimParams::StimParams (const QString & str) [inline]
Definition at line 31 of file StimParams.h.
References fromString().
Member Function Documentation
void StimParams::fromString (const QString & instr)
Parses an ini-stile string to set the params.
Definition at line 7 of file StimParams.cpp.
Referenced by fromFile(), StimApp::loadStim(), and StimParams().
QString StimParams::toString () const
Creates an ini-style multi-line string of the params. Format is as follows:
           name1=value1
           name2=value2
           ...etc...
This is basically the same format at the original StimulateOpenGL configuration file format.
Definition at line 37 of file StimParams.cpp.
bool StimParams::fromFile (const QString & file)
Reads the entire contents of file into memory as a QString then calls fromString() on this string.
Definition at line 47 of file StimParams.cpp.
References fromString(), and str.
The documentation for this class was generated from the following files:
StimParams.h
StimParams.cpp