StimulateOpenGL_II: CalibPlugin Class Reference
CalibPlugin Class Reference
The Refresh Rate Calibration plugin. Calibrates screen refresh rate. Used on Linux only.
#include <CalibPlugin.h>
Signals
void refreshRateCalibrated (unsigned)
Emitted once the plugin has finished calibrating refresh rate. StimApp::caribratedRefresh() is normally connected to this signal (Linux only).
Public Member Functions
QString description () const
returns a string description of the plugin useful for a UI. Reimplement to add a custom description of your plugin.
Protected Member Functions
void drawFrame ()
Draws a random background color to the screen.
bool init ()
Reimplemented from super.
void cleanup ()
Reimplemented from super.
Friends
class GLWindow
Detailed Description
The Refresh Rate Calibration plugin. Calibrates screen refresh rate. Used on Linux only.
This plugin is run by the application on startup to calibrate (determine) the screen refresh rate. On Windows it is not run becasue Windows is able to accurately report refresh rate.
Refresh rate is determined by simply drawing trivial stuff to the screen (in this case, a big rectangle) and measuring the amount of time in between frames. The assumption is that VSync mode is enabled (which is the case in this application).
Once this plugin finishes executing (after 240 frames) it calls stop() on itself and then emits the refreshRateCalibrated() signal which is caught by the StimApp instance.
Definition at line 21 of file CalibPlugin.h.
Member Function Documentation
QString CalibPlugin::description () const [inline, virtual]
returns a string description of the plugin useful for a UI. Reimplement to add a custom description of your plugin.
Reimplemented from StimPlugin.
Definition at line 30 of file CalibPlugin.h.
void CalibPlugin::drawFrame () [protected, virtual]
Draws a random background color to the screen.
Implements StimPlugin.
Definition at line 12 of file CalibPlugin.cpp.
References StimPlugin::finished(), StimPlugin::fps, StimPlugin::fpsAvg, StimPlugin::frameNum, Util::getHWFrameCount(), StimPlugin::height(), StimPlugin::ran1Gen, RNG::range(), refreshRateCalibrated(), StimPlugin::stop(), and StimPlugin::width().
bool CalibPlugin::init () [protected, virtual]
Reimplemented from super.
Reimplemented from StimPlugin.
Definition at line 34 of file CalibPlugin.cpp.
References StimApp::instance(), StimApp::isDebugMode(), StimApp::lockMouseKeyboard(), and StimApp::setDebugMode().
void CalibPlugin::cleanup () [protected, virtual]
Reimplemented from super.
Reimplemented from StimPlugin.
Definition at line 49 of file CalibPlugin.cpp.
References StimApp::instance(), StimApp::releaseMouseKeyboard(), and StimApp::setDebugMode().
void CalibPlugin::refreshRateCalibrated (unsigned) [signal]
Emitted once the plugin has finished calibrating refresh rate. StimApp::caribratedRefresh() is normally connected to this signal (Linux only).
Referenced by drawFrame().
Friends And Related Function Documentation
friend class GLWindow [friend]
Reimplemented from StimPlugin.
Definition at line 25 of file CalibPlugin.h.
The documentation for this class was generated from the following files:
CalibPlugin.h
CalibPlugin.cpp