StimulateOpenGL_II: StimGL_LeoDAQGL_Integration Namespace Reference
StimGL_LeoDAQGL_Integration Namespace Reference
Classes
class NotifyServer
Functions
static QString socketErrorToString (QAbstractSocket::SocketError e)
void setSockContextName (const QString &n)
QString sockContextName ()
bool sockSend (QTcpSocket &sock, const QString &msg, int timeout_msecs, QString *errStr_out=0)
QString sockReadLine (QTcpSocket &sock, int timeout_msecs, QString *errStr_out=0)
static bool doNotify (bool isStart, const QString &pname, const QMap< QString, QVariant > &pparms, QString *errStr_out, const QString &host, unsigned short port, int timeout_msecs)
bool Notify_PluginStart (const QString &pname, const QMap< QString, QVariant > &pparms, QString *errStr_out, const QString &host, unsigned short port, int timeout_msecs)
bool Notify_PluginEnd (const QString &pname, const QMap< QString, QVariant > &pparms, QString *errStr_out, const QString &host, unsigned short port, int timeout_msecs)
Variables
QString sockContextName_ = "Unknown context"
static bool mapMetaTypeRegistered = false
Function Documentation
static bool StimGL_LeoDAQGL_Integration::doNotify (bool isStart, const QString & pname, const QMap< QString, QVariant > & pparms, QString * errStr_out, const QString & host, unsigned short port, int timeout_msecs) [static]
Definition at line 93 of file StimGL_LeoDAQGL_Integration.cpp.
References OK_STRING, PLUGIN_END_STRING, PLUGIN_PARAMS_END_STRING, PLUGIN_PARAMS_STRING, PLUGIN_START_STRING, setSockContextName(), sockContextName(), socketErrorToString(), sockReadLine(), and sockSend().
Referenced by Notify_PluginEnd(), and Notify_PluginStart().
bool StimGL_LeoDAQGL_Integration::Notify_PluginEnd (const QString & pluginName, const QMap< QString, QVariant > & pluginParams, QString * errStr_out = 0, const QString & host = "127.0.0.1", unsigned short port = LEODAQ_GL_NOTIFY_DEFAULT_PORT, int timeout_msecs = LEODAQ_GL_NOTIFY_DEFAULT_TIMEOUT_MSECS)
Called by StimGL to notify LeoDAQGL that a plugin ended. Blocks until the notification is completed, or until timeout expires. Use the errStr_out ptr to QString to determine the error, if any.
Returns:
false if timeout or error, true if succeeded.
Definition at line 149 of file StimGL_LeoDAQGL_Integration.cpp.
References doNotify().
Referenced by StimPlugin::notifySpikeGLAboutStop().
bool StimGL_LeoDAQGL_Integration::Notify_PluginStart (const QString & pluginName, const QMap< QString, QVariant > & pluginParams, QString * errStr_out = 0, const QString & host = "127.0.0.1", unsigned short port = LEODAQ_GL_NOTIFY_DEFAULT_PORT, int timeout_msecs = LEODAQ_GL_NOTIFY_DEFAULT_TIMEOUT_MSECS)
Called by StimGL to notify LeoDAQGL that a plugin started. Blocks until the notification is completed, or until timeout expires. Use the errStr_out ptr to QString to determine the error, if any.
Returns:
false if timeout or error, true if succeeded.
Definition at line 139 of file StimGL_LeoDAQGL_Integration.cpp.
References doNotify().
Referenced by StimPlugin::notifySpikeGLAboutStart().
void StimGL_LeoDAQGL_Integration::setSockContextName (const QString & n)
Definition at line 52 of file StimGL_LeoDAQGL_Integration.cpp.
References sockContextName_.
Referenced by doNotify().
QString StimGL_LeoDAQGL_Integration::sockContextName ()
Definition at line 57 of file StimGL_LeoDAQGL_Integration.cpp.
References sockContextName_.
Referenced by doNotify(), sockReadLine(), and sockSend().
static QString StimGL_LeoDAQGL_Integration::socketErrorToString (QAbstractSocket::SocketError e) [static]
Definition at line 19 of file StimGL_LeoDAQGL_Integration.cpp.
Referenced by doNotify(), and sockSend().
QString StimGL_LeoDAQGL_Integration::sockReadLine (QTcpSocket & sock, int timeout_msecs, QString * errStr_out = 0)
Definition at line 77 of file StimGL_LeoDAQGL_Integration.cpp.
References LINELEN, and sockContextName().
Referenced by doNotify().
bool StimGL_LeoDAQGL_Integration::sockSend (QTcpSocket & sock, const QString & msg, int timeout_msecs, QString * errStr_out = 0)
Definition at line 63 of file StimGL_LeoDAQGL_Integration.cpp.
References sockContextName(), and socketErrorToString().
Referenced by doNotify().
Variable Documentation
bool StimGL_LeoDAQGL_Integration::mapMetaTypeRegistered = false [static]
Definition at line 206 of file StimGL_LeoDAQGL_Integration.cpp.
Referenced by StimGL_LeoDAQGL_Integration::NotifyServer::NotifyServer().
QString StimGL_LeoDAQGL_Integration::sockContextName_ = "Unknown context"
Definition at line 50 of file StimGL_LeoDAQGL_Integration.cpp.
Referenced by setSockContextName(), and sockContextName().