StimulateOpenGL_II: ConnectionThread Class Reference
ConnectionThread Class Reference
A Class that encapsulates a single client connection.
#include <ConnectionThread.h>
Public Member Functions
ConnectionThread (int socketdescr, QObject *parent=0)
Construct a connectionthread given a connected network socket.
bool eventFilter (QObject *, QEvent *)
Reimplemented from QObject so that we can post events to main thread from client threads.
Protected Member Functions
void run ()
This function runs in a separate thread specific to the client and processes incoming requests from the client.
Detailed Description
A Class that encapsulates a single client connection.
This class processes client protocol requests from a separate thread. The run() and processLine() methods do the bulk of the work.
If you want to add protocol commands, you need to modify this class, specifically the processLine() method.
Definition at line 18 of file ConnectionThread.h.
Constructor & Destructor Documentation
ConnectionThread::ConnectionThread (int socketdescr, QObject * parent = 0)
Construct a connectionthread given a connected network socket.
Definition at line 98 of file ConnectionThread.cpp.
Member Function Documentation
bool ConnectionThread::eventFilter (QObject * watched, QEvent * event)
Reimplemented from QObject so that we can post events to main thread from client threads.
reimplemented from QObject so that we can post events to main thread
Definition at line 376 of file ConnectionThread.cpp.
References StimApp::console(), anonymous_namespace{ConnectionThread.cpp}::ConsoleHideEventType, anonymous_namespace{ConnectionThread.cpp}::ConsoleUnHideEventType, StimPlugin::getFrameDump(), anonymous_namespace{ConnectionThread.cpp}::GetFrameEventType, Util::getHWFrameCount(), anonymous_namespace{ConnectionThread.cpp}::GetHWFrameCountEventType, StimApp::glWin(), anonymous_namespace{ConnectionThread.cpp}::IsConsoleHiddenEventType, GLWindow::pluginFind(), GLWindow::runningPlugin(), StimPlugin::start(), anonymous_namespace{ConnectionThread.cpp}::StartPluginEventType, Util::stimApp(), StimPlugin::stop(), and anonymous_namespace{ConnectionThread.cpp}::StopPluginEventType.
void ConnectionThread::run () [protected]
This function runs in a separate thread specific to the client and processes incoming requests from the client.
Reads a line from the socket and passes it off to processLine, if processLine returns a non-null QString, sends it to the client then sends 'OK' otherwise sends 'ERROR' to the client.
Definition at line 104 of file ConnectionThread.cpp.
References StimApp::instance(), and Util::socketNoNagle().
The documentation for this class was generated from the following files:
ConnectionThread.h
ConnectionThread.cpp