StimulateOpenGL_II: CheckerFlicker Class Reference
CheckerFlicker Class Reference
A class for drawing randomly-generated 'checkers' of arbitrary width and height to the GLWindow.
#include <CheckerFlicker.h>
Protected Member Functions
CheckerFlicker ()
can only be constructed by our friend class
~CheckerFlicker ()
void drawFrame ()
Draws the next frame that is already in the texture buffer to the screen.
void afterVSync (bool isSimulated=false)
Informs FrameCreator threads to generate more frames and pops off 1 Frame from a FrameCreator queue and loads it onto the video board using FBO.
bool init ()
Called as a result of start() when plugin is started.
void cleanup ()
Called as a result of stop() when plugin is stopped.
void save ()
default implementation does nothing, reimplement -- called for you on plugin exit if user elected to save data. In this method you should write to the StimPlugin::outStream member.
Friends
class FrameCreator
class GLWindow
Detailed Description
A class for drawing randomly-generated 'checkers' of arbitrary width and height to the GLWindow.
For a full description of this plugin's parameters, it is recommended you see the Plugin Parameter Documentation for more details.
Definition at line 20 of file CheckerFlicker.h.
Constructor & Destructor Documentation
CheckerFlicker::CheckerFlicker () [protected]
can only be constructed by our friend class
Definition at line 235 of file CheckerFlicker.cpp.
CheckerFlicker::~CheckerFlicker () [protected]
Definition at line 240 of file CheckerFlicker.cpp.
Member Function Documentation
void CheckerFlicker::drawFrame () [protected, virtual]
Draws the next frame that is already in the texture buffer to the screen.
Implements StimPlugin.
Definition at line 641 of file CheckerFlicker.cpp.
References StimPlugin::frameNum, and GL_TEXTURE_RECTANGLE_ARB.
void CheckerFlicker::afterVSync (bool isSimulated = false) [protected, virtual]
Informs FrameCreator threads to generate more frames and pops off 1 Frame from a FrameCreator queue and loads it onto the video board using FBO.
Reimplemented from StimPlugin.
Definition at line 701 of file CheckerFlicker.cpp.
References FrameCreator::createMore, StimPlugin::customStatusBarString, StimPlugin::cycleTimeLeft, FrameCreator, StimPlugin::frameNum, Util::getHWFrameCount(), Util::getHWRefreshRate(), Util::getNProcessors(), GL_TEXTURE_RECTANGLE_ARB, FrameCreator::haveMore, MAX, FrameCreator::nWaiting(), FrameCreator::popOne(), and Frame::texels.
bool CheckerFlicker::init () [protected, virtual]
Called as a result of start() when plugin is started.
You should reimplement this in your plugin to add initialization code for class variables, etc. It's important to properly initialize all variables that affect your drawFrame() function so that subsequent runs of the same plugin are identical and not polluted by crufty old state variables. Default implementation does nothing. Return false if you want to indicate init failure for some reason.
Reimplemented from StimPlugin.
Definition at line 269 of file CheckerFlicker.cpp.
References StimApp::console(), StimPlugin::gasGen, Util::getNProcessors(), StimPlugin::getParam(), GL_BGRA, GL_UNSIGNED_INT_8_8_8_8_REV, StimPlugin::ran1Gen, RNG::reseed(), Util::setCurrentThreadAffinityMask(), and Util::stimApp().
void CheckerFlicker::cleanup () [protected, virtual]
Called as a result of stop() when plugin is stopped.
Reimplement to clean up any permanent state that you fear might interfere with other plugins. In general this would only be the OpenGL state that needs to be undone (glEnable/glDisable, etc). Default implementation does nothing.
Reimplemented from StimPlugin.
Definition at line 546 of file CheckerFlicker.cpp.
void CheckerFlicker::save () [protected, virtual]
default implementation does nothing, reimplement -- called for you on plugin exit if user elected to save data. In this method you should write to the StimPlugin::outStream member.
Reimplemented from StimPlugin.
Definition at line 828 of file CheckerFlicker.cpp.
References StimPlugin::outStream.
Friends And Related Function Documentation
friend class FrameCreator [friend]
Definition at line 22 of file CheckerFlicker.h.
Referenced by afterVSync().
friend class GLWindow [friend]
Reimplemented from StimPlugin.
Definition at line 55 of file CheckerFlicker.h.
The documentation for this class was generated from the following files:
CheckerFlicker.h
CheckerFlicker.cpp