StimulateOpenGL_II: RNG Class Reference
RNG Class Reference
A class to generate random numbers.
#include <RNG.h>
Public Types
enum Type { Ran0, Ran1, Gasdev }
Public Member Functions
RNG (int seed=1, Type=Ran0)
~RNG ()
Type type () const
Identify what type of generator this is.
int seed () const
Returns the original seed.
int currentSeed () const
Returns the current seed.
unsigned count () const
Returns the number of times this generator generated a number since it was seeded.
double next ()
int nexti ()
void reseed (int seed)
resets count and sets the seed to seed.
double operator() ()
calls next()
double range (double p1=0., double p2=1.)
Detailed Description
A class to generate random numbers.
Can pick an algorithm & seed at c'tor time and can change seed at runtime.
Currently supports ran0, ran1, and gasdev generators from numerical recipes.
I wanted to encapsulate random number generation in a class to keep different plugins and sets of experiment variables isolated from one another, so that they each have their own random state and seed. This makes reproducing experiments clearer and easier, hopefully. -Calin
Definition at line 17 of file RNG.h.
Member Enumeration Documentation
enum RNG::Type
Enumerator:
Ran0 Numerical recipes ran0() algorithm. Returns a uniformly distributed random number in range (0, 1.00 (0 non-inclusive to 1 non-inclusive).
Ran1 Numerical recipes ran1() algorithm. Returns a uniformly distributed random number in range (0, 1.0) (0 non-inclusive to 1 non-inclusive). Uses a 32-element Bayes-Durham shuffle box to reduce bit correlation.
Gasdev Similar to numerical recipes gasdev() function. Returns a normally distributed random number with mean 0.0 and variance 1.0
Definition at line 20 of file RNG.h.
Constructor & Destructor Documentation
RNG::RNG (int seed = 1, Type t = Ran0)
Definition at line 5 of file RNG.cpp.
References reseed().
RNG::~RNG ()
Definition at line 11 of file RNG.cpp.
Member Function Documentation
unsigned RNG::count () const [inline]
Returns the number of times this generator generated a number since it was seeded.
Definition at line 52 of file RNG.h.
int RNG::currentSeed () const [inline]
Returns the current seed.
Definition at line 49 of file RNG.h.
double RNG::next () [inline]
Generate the next random number. Synonym of operator().
Generation is as follows:
If type() == Ran0 Numerical recipes ran0() algorithm. Returns a uniformly distributed random number in range (0, 1.0) (0 non-inclusive to 1 non-inclusive).
If type() == Ran01 Numerical recipes ran1() algorithm. Returns a uniformly distributed random number in range (0, 1.0) (0 non-inclusive to 1 non-inclusive).
If type() == Gasdev Similar to numerical recipes gasdev() function. Returns a normally distributed random number with mean 0.0 and variance 1.0
Definition at line 72 of file RNG.h.
References Gasdev, Ran0, and Ran1.
Referenced by operator()(), and range().
int RNG::nexti () [inline]
Definition at line 82 of file RNG.h.
References Ran0, and Ran1.
double RNG::operator() () [inline]
calls next()
Definition at line 95 of file RNG.h.
References next().
double RNG::range (double p1 = 0., double p2 = 1.)
Convenience function.
For Ran0 and Ran1 generators:
This uses next() to return a random number in range [p1, p2). Note how this range differs in how it is inclusive from the next() function. (It is inclusive of p1 and not inclusive of p2). [Undefined if p1 > p2.]
Note this is slightly slower than calling next() because it scales the results of next() to modify the range of the output.
The way this function is inclusive is more useful for some programmers since traditionally programmers like to start at min (inclusive) and go to max non-inclusively.
For Gasdev generators:
Uses next() to return a random number with mean p1 and stddev p2.
Definition at line 41 of file RNG.cpp.
References Gasdev, and next().
Referenced by CalibPlugin::drawFrame().
void RNG::reseed (int seed)
resets count and sets the seed to seed.
Definition at line 29 of file RNG.cpp.
Referenced by MovingObjects::init(), CheckerFlicker::init(), and RNG().
int RNG::seed () const [inline]
Returns the original seed.
Definition at line 46 of file RNG.h.
Type RNG::type () const [inline]
Identify what type of generator this is.
Definition at line 43 of file RNG.h.
The documentation for this class was generated from the following files:
RNG.h
RNG.cpp