StimulateOpenGL_II: StimApp Class Reference
StimApp Class Reference
The central class to the program that more-or-less encapsulates most objects and data in the program.
#include <StimApp.h>
Public Types
enum EventsTypes { LogLineEventType = QEvent::User, StatusMsgEventType, QuitEventType }
Public Slots
void setDebugMode (bool)
Set/unset the application-wide 'debug' mode setting. If the application is in debug mode, Debug() messages are printed to the console window, otherwise they are not.
void loadStim ()
Pops up a UI so that the user can select a stim. config file to load.
void unloadStim ()
Unloads/stops the currently running plugin and may prompt the user to save.
void about ()
Pops up the application "About" dialog box.
void pickOutputDir ()
Prompts the user to pick a save directory.
void pauseUnpause ()
Calls GLWindow::pauseUnpause().
void hideUnhideConsole ()
Toggles the console window hidden/shown state.
void alignGLWindow ()
Aligns the GLWindow to the screen's top-left corner. ('A' hotkey in the UI.).
void leoDAQGLIntegrationDialog ()
Pops up the LeoDAQGL integration options dialog and sets the params based on this Window.
Public Member Functions
virtual ~StimApp ()
GLWindow * glWin () const
Returns a pointer to the application-wide GLWindow instance.
ConsoleWindow * console () const
Returns a pointer to the application-wide ConsoleWindow instance.
bool isDebugMode () const
Returns true iff the application's console window has debug output printing enabled.
QString outputDirectory () const
Returns the directory under which all plugin data files are to be saved.
bool setOutputDirectory (const QString &dpath)
Set the directory under which all plugin data files are to be saved. NB: dpath must exist otherwise it is not set and false is returned.
void logLine (const QString &line, const QColor &=QColor())
Thread-safe logging -- logs a line to the log window in a thread-safe manner.
void statusMsg (const QString &message, int timeout_msecs=0)
Display a message to the status bar.
bool eventFilter (QObject *watched, QEvent *event)
Used to catch various events from other threads, etc.
unsigned refreshRate () const
Returns the refresh rate for the monitor that the GLWindow is currently sitting in, as reported by Windows.
bool busy () const
Returns true if and only if the application is still initializing and not done with its startup. This is mainly used by the socket connection code to make incoming connections stall until the application is finished initializing.
Static Public Member Functions
static StimApp * instance ()
Returns a pointer to the singleton instance of this class, if one exists, otherwise returns 0.
static void lockMouseKeyboard ()
Use this function to completely lock the mouse and keyboard -- useful if performing a task that must not be interrupted by the user. Use sparingly!
static void releaseMouseKeyboard ()
Undo the damage done by a lockMouseKeyboard() call.
Public Attributes
struct
StimApp::LeoDAQGLNotifyParams leoDAQGLNotifyParams
Protected Slots
void updateStatusBar ()
Called from a timer every ~250 ms to update the status bar at the bottom of the console window.
void quitCleanup ()
Friends
int main (int, char **)
Classes
struct LeoDAQGLNotifyParams
Some parameters related to the external LeoDAQGL program notification.
Detailed Description
The central class to the program that more-or-less encapsulates most objects and data in the program.
This class inherits from QApplication for simplicity. It is sort of a central place that other parts of the program use to find settings, pointers to other windows, and various other application-wide data.
Definition at line 45 of file StimApp.h.
Member Enumeration Documentation
enum StimApp::EventsTypes
Enumerator:
LogLineEventType used to catch log line events see StimApp.cpp
StatusMsgEventType used to indicate the event contains a status message for the status bar
QuitEventType so we can post quit events..
Definition at line 89 of file StimApp.h.
Constructor & Destructor Documentation
StimApp::~StimApp () [virtual]
Definition at line 188 of file StimApp.cpp.
Member Function Documentation
static StimApp* StimApp::instance () [inline, static]
Returns a pointer to the singleton instance of this class, if one exists, otherwise returns 0.
Definition at line 54 of file StimApp.h.
Referenced by CalibPlugin::cleanup(), CalibPlugin::init(), lockMouseKeyboard(), ConnectionThread::run(), Util::stimApp(), and StimPlugin::~StimPlugin().
GLWindow* StimApp::glWin () const [inline]
Returns a pointer to the application-wide GLWindow instance.
Definition at line 67 of file StimApp.h.
Referenced by ConnectionThread::eventFilter(), Util::glGetErrorString(), and Util::hasExt().
ConsoleWindow* StimApp::console () const [inline]
Returns a pointer to the application-wide ConsoleWindow instance.
Definition at line 70 of file StimApp.h.
Referenced by ConnectionThread::eventFilter(), CheckerFlicker::init(), and lockMouseKeyboard().
bool StimApp::isDebugMode () const
Returns true iff the application's console window has debug output printing enabled.
Definition at line 203 of file StimApp.cpp.
Referenced by CalibPlugin::init().
QString StimApp::outputDirectory () const [inline]
Returns the directory under which all plugin data files are to be saved.
Definition at line 76 of file StimApp.h.
bool StimApp::setOutputDirectory (const QString & dpath)
Set the directory under which all plugin data files are to be saved. NB: dpath must exist otherwise it is not set and false is returned.
Definition at line 513 of file StimApp.cpp.
void StimApp::logLine (const QString & line, const QColor & c = QColor())
Thread-safe logging -- logs a line to the log window in a thread-safe manner.
Definition at line 280 of file StimApp.cpp.
Referenced by Util::Log::~Log().
void StimApp::statusMsg (const QString & message, int timeout_msecs = 0)
Display a message to the status bar.
Definition at line 366 of file StimApp.cpp.
Referenced by Util::Status::~Status().
bool StimApp::eventFilter (QObject * watched, QEvent * event)
Used to catch various events from other threads, etc.
Definition at line 215 of file StimApp.cpp.
References LogLineEventType, MAX, QuitEventType, StatusMsgEventType, and ConsoleWindow::textEdit().
unsigned StimApp::refreshRate () const [inline]
Returns the refresh rate for the monitor that the GLWindow is currently sitting in, as reported by Windows.
Definition at line 99 of file StimApp.h.
Referenced by GLWindow::paintGL().
void StimApp::lockMouseKeyboard () [static]
Use this function to completely lock the mouse and keyboard -- useful if performing a task that must not be interrupted by the user. Use sparingly!
Definition at line 351 of file StimApp.cpp.
References console(), and instance().
Referenced by CalibPlugin::init().
void StimApp::releaseMouseKeyboard () [static]
Undo the damage done by a lockMouseKeyboard() call.
Definition at line 358 of file StimApp.cpp.
Referenced by CalibPlugin::cleanup().
bool StimApp::busy () const [inline]
Returns true if and only if the application is still initializing and not done with its startup. This is mainly used by the socket connection code to make incoming connections stall until the application is finished initializing.
Definition at line 107 of file StimApp.h.
void StimApp::setDebugMode (bool d) [slot]
Set/unset the application-wide 'debug' mode setting. If the application is in debug mode, Debug() messages are printed to the console window, otherwise they are not.
Definition at line 209 of file StimApp.cpp.
Referenced by CalibPlugin::cleanup(), CalibPlugin::init(), and GLWindow::keyPressEvent().
void StimApp::loadStim () [slot]
Pops up a UI so that the user can select a stim. config file to load.
Definition at line 410 of file StimApp.cpp.
References DEFAULT_WIN_SIZE, StimParams::fromString(), StimPlugin::getFrameNum(), StimPlugin::name(), GLWindow::pluginFind(), GLWindow::runningPlugin(), StimPlugin::setParams(), StimPlugin::start(), and StimPlugin::stop().
void StimApp::unloadStim () [slot]
Unloads/stops the currently running plugin and may prompt the user to save.
Definition at line 480 of file StimApp.cpp.
void StimApp::about () [slot]
Pops up the application "About" dialog box.
Definition at line 503 of file StimApp.cpp.
void StimApp::pickOutputDir () [slot]
Prompts the user to pick a save directory.
See also:
setOutputDirectory
outputDirectory
Definition at line 523 of file StimApp.cpp.
void StimApp::pauseUnpause () [slot]
Calls GLWindow::pauseUnpause().
Definition at line 560 of file StimApp.cpp.
Referenced by GLWindow::keyPressEvent().
void StimApp::hideUnhideConsole () [slot]
Toggles the console window hidden/shown state.
Definition at line 565 of file StimApp.cpp.
Referenced by GLWindow::keyPressEvent().
void StimApp::alignGLWindow () [slot]
Aligns the GLWindow to the screen's top-left corner. ('A' hotkey in the UI.).
Definition at line 577 of file StimApp.cpp.
void StimApp::leoDAQGLIntegrationDialog () [slot]
Pops up the LeoDAQGL integration options dialog and sets the params based on this Window.
Definition at line 610 of file StimApp.cpp.
void StimApp::updateStatusBar () [protected, slot]
Called from a timer every ~250 ms to update the status bar at the bottom of the console window.
Definition at line 371 of file StimApp.cpp.
void StimApp::quitCleanup () [protected, slot]
Definition at line 196 of file StimApp.cpp.
Friends And Related Function Documentation
int main (int , char **) [friend]
Member Data Documentation
struct StimApp::LeoDAQGLNotifyParams StimApp::leoDAQGLNotifyParams
Referenced by CalibPlugin::start(), and CalibPlugin::stop().
The documentation for this class was generated from the following files:
StimApp.h
StimApp.cpp