StimulateOpenGL_II: Util Namespace Reference
Util Namespace Reference
Various global utility functions used application-wide.
Classes
class Log
Super class of Debug, Warning, Error classes.
class Debug
Stream-like class to print a debug message to the app's console window Example:.
class Error
Stream-like class to print an error message to the app's console window Example:.
class Warning
Stream-like class to print a warning message to the app's console window.
class Status
Stream-like class to print a message to the app's status bar.
Functions
void setRTPriority ()
set the current process to realtime priority, implemented in osdep.cpp
double getTime ()
retrieve a time value from the system's high resolution timer
void setProcessAffinityMask (unsigned mask)
sets the process affinity mask -- a bitset of which processors to run on
static const GLubyte * strChr (const GLubyte *str, GLubyte ch)
static const char * gl_error_str (GLenum err)
bool hasExt (const char *gl_ext)
return true iff opengl has the X ext gl_ext
bool hasAccurateHWFrameCount ()
True if the platform has a hardware framecount function.
unsigned getNProcessors ()
returns the number of real CPUs (cores) on the system
unsigned getHWFrameCount ()
retrieve the frame count from the GLX_SGI_video_sync ext
unsigned getHWRefreshRate ()
retrieve the refresh rate from HW (implemented in osdep.cpp)
bool hasAccurateHWRefreshRate ()
True if the platform we are running on has a 'get refresh rate' function.
QString getHostName ()
returns the current host name
void socketNoNagle (int sock)
turns off Nagle algorithm for socket sock
unsigned getUpTime ()
returns the number of seconds since this machine last rebooted
unsigned setCurrentThreadAffinityMask (unsigned mask)
void Connect (QObject *srco, const QString &src, QObject *desto, const QString &dest)
StimApp * stimApp ()
Returns a pointer to the StimApp singleton instance.
QString glGetErrorString (int err)
returns a QString signifying the last error error
double random (double min=0., double max=1.)
std::rand() based random number from [min, max].
void setVSyncMode ()
Enable vsync.
Variables
static int fc_is_accurate = -1
Detailed Description
Various global utility functions used application-wide.
Function Documentation
void Util::Connect (QObject * srcobj, const QString & src_signal, QObject * destobj, const QString & dest_slot)
Just like QObject::connect except it will popup an error box if there was a problem connecting, and exit the program immediately
Definition at line 27 of file Util.cpp.
Referenced by StimGL_LeoDAQGL_Integration::NotifyServer::NotifyServer().
QString Util::getHostName ()
returns the current host name
Definition at line 434 of file osdep.cpp.
unsigned Util::getHWFrameCount ()
retrieve the frame count from the GLX_SGI_video_sync ext
Definition at line 357 of file osdep.cpp.
Referenced by CheckerFlicker::afterVSync(), CalibPlugin::drawFrame(), ConnectionThread::eventFilter(), hasAccurateHWFrameCount(), and GLWindow::paintGL().
unsigned Util::getHWRefreshRate ()
retrieve the refresh rate from HW (implemented in osdep.cpp)
Definition at line 385 of file osdep.cpp.
References stimApp().
Referenced by CheckerFlicker::afterVSync(), StimPlugin::getFrameDump(), and GLWindow::paintGL().
unsigned Util::getNProcessors ()
returns the number of real CPUs (cores) on the system
Definition at line 293 of file osdep.cpp.
Referenced by CheckerFlicker::afterVSync(), CheckerFlicker::init(), GLWindow::paintGL(), and FrameCreator::run().
double Util::getTime ()
retrieve a time value from the system's high resolution timer
Definition at line 62 of file osdep.cpp.
Referenced by StimPlugin::getFrameDump(), anonymous_namespace{osdep.cpp}::Init::Init(), and GLWindow::paintGL().
unsigned Util::getUpTime ()
returns the number of seconds since this machine last rebooted
Definition at line 462 of file osdep.cpp.
static const char* Util::gl_error_str (GLenum err) [static]
Definition at line 157 of file osdep.cpp.
Referenced by hasExt().
QString Util::glGetErrorString (int err)
returns a QString signifying the last error error
Definition at line 44 of file Util.cpp.
References StimApp::glWin(), and stimApp().
bool Util::hasAccurateHWFrameCount ()
True if the platform has a hardware framecount function.
true on platforms like linux that has the glXGetVideoSyncSGI function false on windows and platforms lacking this glX function
Definition at line 286 of file osdep.cpp.
References fc_is_accurate, and getHWFrameCount().
Referenced by GLWindow::paintGL().
bool Util::hasAccurateHWRefreshRate ()
True if the platform we are running on has a 'get refresh rate' function.
true on Windows false on others
Definition at line 413 of file osdep.cpp.
bool Util::hasExt (const char * ext_name)
return true iff opengl has the X ext gl_ext
Definition at line 182 of file osdep.cpp.
References gl_error_str(), StimApp::glWin(), stimApp(), and strChr().
double Util::random (double min = 0., double max = 1.)
std::rand() based random number from [min, max].
You don't formally want to use this. See the RNG class instead.
Definition at line 106 of file Util.cpp.
unsigned Util::setCurrentThreadAffinityMask (unsigned cpu_mask)
`Pins' the current thread to a particular set of processors, that is, makes it only run on a particular set of processors. returns 0 on error, or the previous mask on success.
Definition at line 485 of file osdep.cpp.
Referenced by CheckerFlicker::init(), and FrameCreator::run().
void Util::setProcessAffinityMask (unsigned mask)
sets the process affinity mask -- a bitset of which processors to run on
Definition at line 76 of file osdep.cpp.
void Util::setRTPriority ()
set the current process to realtime priority, implemented in osdep.cpp
Definition at line 56 of file osdep.cpp.
void Util::setVSyncMode ()
Enable vsync.
Set the opengl mode to synchronize with the vertical blank signal -- implemented in osdep.cpp
void Util::socketNoNagle (int sock)
turns off Nagle algorithm for socket sock
Definition at line 441 of file osdep.cpp.
Referenced by ConnectionThread::run().
StimApp * Util::stimApp ()
Returns a pointer to the StimApp singleton instance.
Definition at line 38 of file Util.cpp.
References StimApp::instance().
Referenced by GLWindow::closeEvent(), ConsoleWindow::ConsoleWindow(), ConnectionThread::eventFilter(), getHWRefreshRate(), glGetErrorString(), hasExt(), CheckerFlicker::init(), GLWindow::keyPressEvent(), StimPlugin::notifySpikeGLAboutStart(), StimPlugin::notifySpikeGLAboutStop(), GLWindow::paintGL(), StimPlugin::start(), CalibPlugin::start(), StimPlugin::stop(), CalibPlugin::stop(), Util::Debug::~Debug(), Util::Log::~Log(), and Util::Status::~Status().
static const GLubyte* Util::strChr (const GLubyte * str, GLubyte ch) [static]
Definition at line 151 of file osdep.cpp.
Referenced by hasExt().
Variable Documentation
int Util::fc_is_accurate = -1 [static]
Definition at line 284 of file osdep.cpp.
Referenced by hasAccurateHWFrameCount().