StimulateOpenGL_II: MovingObjects Class Reference
MovingObjects Class Reference
A plugin that draws an moving target.
#include <MovingObjects.h>
Public Member Functions
virtual ~MovingObjects ()
Protected Member Functions
bool init ()
reimplemented from super
void cleanup ()
reimplemented from super
void drawFrame ()
reimplemented
bool processKey (int key)
remiplemented
Friends
class GLWindow
Detailed Description
A plugin that draws an moving target.
This plugin basically draws a moving target in the GLWindow, which has its own trajectory and which bounces when it reaches the edge of the GLWindow.
The target may be a circle or a box.
A variety of parameters control this plugin's operation, and it is recommended you see the Plugin Parameter Documentation for more details.
Definition at line 16 of file MovingObjects.h.
Constructor & Destructor Documentation
MovingObjects::~MovingObjects () [virtual]
Definition at line 8 of file MovingObjects.cpp.
Member Function Documentation
bool MovingObjects::init () [protected, virtual]
reimplemented from super
Reimplemented from StimPlugin.
Definition at line 12 of file MovingObjects.cpp.
References StimPlugin::getParam(), StimPlugin::height(), StimPlugin::ran1Gen, RNG::reseed(), and StimPlugin::width().
void MovingObjects::cleanup () [protected, virtual]
reimplemented from super
Reimplemented from StimPlugin.
Definition at line 116 of file MovingObjects.cpp.
void MovingObjects::drawFrame () [protected, virtual]
reimplemented
Implements StimPlugin.
Definition at line 139 of file MovingObjects.cpp.
References StimPlugin::frameNum, and StimPlugin::ran1Gen.
bool MovingObjects::processKey (int key) [protected, virtual]
remiplemented
Reimplemented from StimPlugin.
Definition at line 122 of file MovingObjects.cpp.
References StimPlugin::processKey().
Friends And Related Function Documentation
friend class GLWindow [friend]
Reimplemented from StimPlugin.
Definition at line 18 of file MovingObjects.h.
The documentation for this class was generated from the following files:
MovingObjects.h
MovingObjects.cpp