StimulateOpenGL_II: StimPlugin Class Reference
StimPlugin Class Reference
Abstract class -- inherit from this class to create a plugin.
#include <StimPlugin.h>
Signals
void started ()
emitted when plugin starts
void finished ()
emitted when plugin finishes naturally
void stopped ()
emitted whenever plugin stops
Public Member Functions
virtual ~StimPlugin ()
virtual unsigned preferredFPS () const
iff 0, this plugin runs as fast as possible (up to monitor refresh rate)
unsigned width () const
returns width in pixels of the opengl 2d area
unsigned height () const
returns height in pixels of the opengl 2d area
virtual void start (bool startUnpaused=false)
start the plugin -- marks the plugin as 'running' with the GLWindow and calls init(), then emits 'started' signal. If reimplementing, call super.
virtual void stop (bool doSave=false, bool use_gui=false)
stop the plugin -- marks the plugin as 'not running' with the GLWindow, calls cleanup(), then emits 'stopped' signal. If reimplementig, call super
QString name () const
just calls QObject::objectName()
virtual QString description () const
returns a string description of the plugin useful for a UI. Reimplement to add a custom description of your plugin.
void setParams (const StimParams &p)
Set the plugin's configuration parameters. ConnectonThread calls this method for example when the client wants to define experiment parameters for a plugin.
StimParams getParams () const
We return an implicitly shared copy of the parameters. Due to multithreading concerns, implicit sharing is a good thing!
template<typename T>
bool getParam (const QString &name, T &out) const
templatized function for reading parameters
double getFps () const
Returns the average FPS for this plugin over the last 1-2 seconds.
double getFpsCur () const
Returns the latest FPS for this plugin (over the last 2 frames).
double getFpsMin () const
Returns the smallest FPS value encountered since plugin start().
double getFpsMax () const
Returns the largest FPS value encounteres since plugin start().
unsigned getNextFrameNum () const
Returns the frame number of the next frame to be rendered.
int getFrameNum () const
Returns the frame number of the last frame that was rendered (or -1 if no frame has ever been rendered).
const QString & getSBString () const
Returns the status bar string that this plugin would like the UI to display.
unsigned getNumMissedFrames () const
Returns the number of missed frames that the plugin has encountered thus far.
QDateTime getBeginTime () const
Returns the time that start() was called for this plugin.
bool saveData (bool use_gui_for_errors=false)
Save pluign date to a file.
QByteArray getFrameDump (unsigned num, GLenum data_type=GL_UNSIGNED_BYTE)
Grab arbitrary frame data by number from a plugin.
Protected Member Functions
StimPlugin (const QString &name)
virtual bool processKey (int key)
virtual bool init ()
Called as a result of start() when plugin is started.
virtual void cleanup ()
Called as a result of stop() when plugin is stopped.
virtual void drawFrame ()=0
The meat of every plugin -- re-implement this function to draw the actual frame. Class variable frameNum holds the frame number.
virtual void afterVSync (bool isSimulated=false)
Called immediately after a vsync (if not paused).
void notifySpikeGLAboutStart ()
void notifySpikeGLAboutStop ()
virtual void save ()
default implementation does nothing, reimplement -- called for you on plugin exit if user elected to save data. In this method you should write to the StimPlugin::outStream member.
void putMissedFrame (unsigned cycleTimeMsecs)
called by GLWindow when a frameskip is detected..
Protected Attributes
GLWindow * parent
unsigned frameNum
starts at 0 and gets incremented for each frame (each time drawFrame() is called)
double fps
double fpsAvg
double fpsMin
double fpsMax
double cycleTimeLeft
the number of seconds left in this cycle -- updated by glWindow before calling afterVSync
bool needNotifyStart
iff true, we will notify LeoDAQGL of plugin start on unpause
QMutex mut
plugin-level mutex -- used in a couple of functions and you may reuse it yourself as well
std::vector< unsigned > missedFrames
std::vector< unsigned > missedFrameTimes
a list of cycle times for skipped/missed frames, in msecs
RNG ran1Gen
Generic random number generator provided here as a convenience.
RNG gasGen
Generic gaussian random number generator provided here as a convenience.
RNG ran0Gen
Generic random number generator provided here as a convenience.
QString customStatusBarString
Write to this variable to optionally inform the application that you want a custom message printed to the status bar.
QTextStream outStream
the output stream you should use in your "save()" method reimplementation -- already opened for you if your save() method is being called
QFile outFile
Write to this file when saving data.
QDateTime begintime
QDateTime endtime
Friends
class GLWindow
Detailed Description
Abstract class -- inherit from this class to create a plugin.
See MovingObjects, MovingGrating, and CheckerFlicker for some pre-existing plugins.
Once you inherit from this class, you need to implement at least the the drawFrame() method to generate frames. Your method is called for you from the GLWindow::paintGL() fuction, once per vblank while your plugin is running.
You may put any setup code you wish to execute on plugin startup in your reimplementation of the init() method.
Any cleanup code should go in your reimplementation of the cleanup() method.
Access your plugin's configuration parameters with getParam().
Note that in order for plugins you write to appear in the main application, they need to be also created (new'd) inside GLWindow::initPlugin().
Definition at line 56 of file StimPlugin.h.
Constructor & Destructor Documentation
StimPlugin::StimPlugin (const QString & name) [protected]
Definition at line 9 of file StimPlugin.cpp.
References frameNum, needNotifyStart, parent, and GLWindow::pluginCreated().
StimPlugin::~StimPlugin () [virtual]
Definition at line 18 of file StimPlugin.cpp.
References StimApp::instance(), parent, GLWindow::pluginDeleted(), GLWindow::runningPlugin(), and stop().
Member Function Documentation
virtual unsigned StimPlugin::preferredFPS () const [inline, virtual]
iff 0, this plugin runs as fast as possible (up to monitor refresh rate)
Definition at line 69 of file StimPlugin.h.
unsigned StimPlugin::width () const
returns width in pixels of the opengl 2d area
Definition at line 104 of file StimPlugin.cpp.
References parent.
Referenced by CalibPlugin::drawFrame(), getFrameDump(), and MovingObjects::init().
unsigned StimPlugin::height () const
returns height in pixels of the opengl 2d area
Definition at line 109 of file StimPlugin.cpp.
References parent.
Referenced by CalibPlugin::drawFrame(), getFrameDump(), and MovingObjects::init().
void StimPlugin::start (bool startUnpaused = false) [virtual]
start the plugin -- marks the plugin as 'running' with the GLWindow and calls init(), then emits 'started' signal. If reimplementing, call super.
Reimplemented in CalibPlugin.
Definition at line 64 of file StimPlugin.cpp.
References begintime, customStatusBarString, endtime, fps, fpsAvg, fpsMax, fpsMin, frameNum, init(), missedFrames, missedFrameTimes, name(), needNotifyStart, notifySpikeGLAboutStart(), parent, GLWindow::pauseUnpause(), GLWindow::pluginStarted(), started(), Util::stimApp(), and stop().
Referenced by ConnectionThread::eventFilter(), getFrameDump(), StimApp::loadStim(), and CalibPlugin::start().
void StimPlugin::stop (bool doSave = false, bool use_gui = false) [virtual]
stop the plugin -- marks the plugin as 'not running' with the GLWindow, calls cleanup(), then emits 'stopped' signal. If reimplementig, call super
Reimplemented in CalibPlugin.
Definition at line 38 of file StimPlugin.cpp.
References cleanup(), endtime, frameNum, notifySpikeGLAboutStop(), parent, GLWindow::pluginStopped(), saveData(), Util::stimApp(), and stopped().
Referenced by ConnectionThread::eventFilter(), getFrameDump(), StimApp::loadStim(), GLWindow::pluginStarted(), start(), GridPlugin::stop(), CalibPlugin::stop(), GLWindow::~GLWindow(), and ~StimPlugin().
QString StimPlugin::name () const [inline]
just calls QObject::objectName()
Definition at line 82 of file StimPlugin.h.
Referenced by getFrameDump(), StimApp::loadStim(), notifySpikeGLAboutStart(), notifySpikeGLAboutStop(), GLWindow::pluginStarted(), GLWindow::pluginStopped(), saveData(), and start().
virtual QString StimPlugin::description () const [inline, virtual]
returns a string description of the plugin useful for a UI. Reimplement to add a custom description of your plugin.
Reimplemented in CalibPlugin.
Definition at line 84 of file StimPlugin.h.
void StimPlugin::setParams (const StimParams & p) [inline]
Set the plugin's configuration parameters. ConnectonThread calls this method for example when the client wants to define experiment parameters for a plugin.
Definition at line 87 of file StimPlugin.h.
References mut.
Referenced by StimApp::loadStim().
StimParams StimPlugin::getParams () const [inline]
We return an implicitly shared copy of the parameters. Due to multithreading concerns, implicit sharing is a good thing!
Definition at line 89 of file StimPlugin.h.
References mut.
Referenced by notifySpikeGLAboutStart(), and notifySpikeGLAboutStop().
template<typename T> bool StimPlugin::getParam (const QString & name, T & out) const [inline]
templatized function for reading parameters
Definition at line 278 of file StimPlugin.h.
References mut.
Referenced by MovingObjects::init(), MovingGrating::init(), and CheckerFlicker::init().
double StimPlugin::getFps () const [inline]
Returns the average FPS for this plugin over the last 1-2 seconds.
Definition at line 95 of file StimPlugin.h.
References fpsAvg.
double StimPlugin::getFpsCur () const [inline]
Returns the latest FPS for this plugin (over the last 2 frames).
Definition at line 97 of file StimPlugin.h.
References fps.
double StimPlugin::getFpsMin () const [inline]
Returns the smallest FPS value encountered since plugin start().
Definition at line 99 of file StimPlugin.h.
References fpsMin.
double StimPlugin::getFpsMax () const [inline]
Returns the largest FPS value encounteres since plugin start().
Definition at line 101 of file StimPlugin.h.
References fpsMax.
unsigned StimPlugin::getNextFrameNum () const [inline]
Returns the frame number of the next frame to be rendered.
Definition at line 103 of file StimPlugin.h.
References frameNum.
int StimPlugin::getFrameNum () const [inline]
Returns the frame number of the last frame that was rendered (or -1 if no frame has ever been rendered).
Definition at line 105 of file StimPlugin.h.
References frameNum.
Referenced by StimApp::loadStim().
const QString& StimPlugin::getSBString () const [inline]
Returns the status bar string that this plugin would like the UI to display.
Definition at line 107 of file StimPlugin.h.
References customStatusBarString.
unsigned StimPlugin::getNumMissedFrames () const [inline]
Returns the number of missed frames that the plugin has encountered thus far.
Definition at line 109 of file StimPlugin.h.
References missedFrames.
QDateTime StimPlugin::getBeginTime () const [inline]
Returns the time that start() was called for this plugin.
Definition at line 112 of file StimPlugin.h.
References begintime.
bool StimPlugin::saveData (bool use_gui_for_errors = false)
Save pluign date to a file.
Save data -- called for you on if plugin stop(true). Returns false on error (usually failure to open output files). Use gui parameter controls whether to use the GUI for reporting/ recovering from errors (or to just silently return false on error).
Definition at line 28 of file StimPlugin.cpp.
References name(), outFile, and save().
Referenced by stop().
QByteArray StimPlugin::getFrameDump (unsigned num, GLenum data_type = GL_UNSIGNED_BYTE)
Grab arbitrary frame data by number from a plugin.
from an experiment. Note that it's best to call this with num increasing by 1 each time (that is, sequentially) as otherwise you may experience long delays while the plugin recomputes all frames up to num.
Parameters:
num the frame number to generate/dump
data_type the OpenGL data type of the generated data. Note that the default is good for most users so no need to change it unless you know what you are doing.
Definition at line 196 of file StimPlugin.cpp.
References afterVSync(), cycleTimeLeft, drawFrame(), frameNum, Util::getHWRefreshRate(), Util::getTime(), height(), GLWindow::isPaused(), name(), parent, GLWindow::runningPlugin(), start(), stop(), and width().
Referenced by ConnectionThread::eventFilter().
void StimPlugin::started () [signal]
emitted when plugin starts
Referenced by start().
void StimPlugin::finished () [signal]
emitted when plugin finishes naturally
Referenced by CalibPlugin::drawFrame().
void StimPlugin::stopped () [signal]
emitted whenever plugin stops
Referenced by stop().
virtual bool StimPlugin::processKey (int key) [inline, protected, virtual]
Process keypresses. Reimplement this in your plugin to process keys: Return true if key processed (accepted) or false otherwise. NB: It's important to return false if you want to ignore the key so other widgets can receive it. If you return true no other widgets are notified of the keypress.
Reimplemented in MovingObjects.
Definition at line 145 of file StimPlugin.h.
Referenced by GLWindow::keyPressEvent(), and MovingObjects::processKey().
bool StimPlugin::init () [protected, virtual]
Called as a result of start() when plugin is started.
You should reimplement this in your plugin to add initialization code for class variables, etc. It's important to properly initialize all variables that affect your drawFrame() function so that subsequent runs of the same plugin are identical and not polluted by crufty old state variables. Default implementation does nothing. Return false if you want to indicate init failure for some reason.
Reimplemented in CalibPlugin, CheckerFlicker, MovingGrating, and MovingObjects.
Definition at line 25 of file StimPlugin.cpp.
Referenced by start().
void StimPlugin::cleanup () [protected, virtual]
Called as a result of stop() when plugin is stopped.
Reimplement to clean up any permanent state that you fear might interfere with other plugins. In general this would only be the OpenGL state that needs to be undone (glEnable/glDisable, etc). Default implementation does nothing.
Reimplemented in CalibPlugin, CheckerFlicker, and MovingObjects.
Definition at line 26 of file StimPlugin.cpp.
Referenced by stop().
virtual void StimPlugin::drawFrame () [protected, pure virtual]
The meat of every plugin -- re-implement this function to draw the actual frame. Class variable frameNum holds the frame number.
Implemented in CalibPlugin, CheckerFlicker, MovingGrating, and MovingObjects.
Referenced by getFrameDump(), and GLWindow::paintGL().
void StimPlugin::afterVSync (bool isSimulated = false) [protected, virtual]
Called immediately after a vsync (if not paused).
Reimplement this in your plugin to do some work after the vsync, which may be a good time to do slower computations in preparation for the next frame, etc, since we have the maximal amount of time at this point before the next frame is to be drawn. If isSimulated = true this means we are in getFrameNum() call and not actually drawing to screen.
Reimplemented in CheckerFlicker.
Definition at line 132 of file StimPlugin.cpp.
Referenced by getFrameDump(), and GLWindow::paintGL().
void StimPlugin::notifySpikeGLAboutStart () [protected]
Definition at line 250 of file StimPlugin.cpp.
References getParams(), StimApp::LeoDAQGLNotifyParams::hostname, name(), needNotifyStart, StimGL_LeoDAQGL_Integration::Notify_PluginStart(), StimApp::LeoDAQGLNotifyParams::port, Util::stimApp(), and StimApp::LeoDAQGLNotifyParams::timeout_ms.
Referenced by GLWindow::pauseUnpause(), and start().
void StimPlugin::notifySpikeGLAboutStop () [protected]
Definition at line 262 of file StimPlugin.cpp.
References getParams(), StimApp::LeoDAQGLNotifyParams::hostname, name(), needNotifyStart, StimGL_LeoDAQGL_Integration::Notify_PluginEnd(), StimApp::LeoDAQGLNotifyParams::port, Util::stimApp(), and StimApp::LeoDAQGLNotifyParams::timeout_ms.
Referenced by stop().
virtual void StimPlugin::save () [inline, protected, virtual]
default implementation does nothing, reimplement -- called for you on plugin exit if user elected to save data. In this method you should write to the StimPlugin::outStream member.
Reimplemented in CheckerFlicker.
Definition at line 228 of file StimPlugin.h.
Referenced by saveData().
void StimPlugin::putMissedFrame (unsigned cycleTimeMsecs) [protected]
called by GLWindow when a frameskip is detected..
Definition at line 186 of file StimPlugin.cpp.
References frameNum, missedFrames, and missedFrameTimes.
Referenced by GLWindow::paintGL().
Friends And Related Function Documentation
friend class GLWindow [friend]
Reimplemented in CalibPlugin, CheckerFlicker, MovingGrating, and MovingObjects.
Definition at line 60 of file StimPlugin.h.
Member Data Documentation
GLWindow* StimPlugin::parent [protected]
Definition at line 178 of file StimPlugin.h.
Referenced by getFrameDump(), height(), start(), StimPlugin(), stop(), width(), and ~StimPlugin().
unsigned StimPlugin::frameNum [protected]
starts at 0 and gets incremented for each frame (each time drawFrame() is called)
Definition at line 180 of file StimPlugin.h.
Referenced by CheckerFlicker::afterVSync(), MovingObjects::drawFrame(), CheckerFlicker::drawFrame(), CalibPlugin::drawFrame(), getFrameDump(), getFrameNum(), getNextFrameNum(), GLWindow::paintGL(), GLWindow::pauseUnpause(), putMissedFrame(), start(), StimPlugin(), and stop().
double StimPlugin::fps [protected]
Definition at line 181 of file StimPlugin.h.
Referenced by CalibPlugin::drawFrame(), getFpsCur(), and start().
double StimPlugin::fpsAvg [protected]
Definition at line 181 of file StimPlugin.h.
Referenced by CalibPlugin::drawFrame(), getFps(), and start().
double StimPlugin::fpsMin [protected]
Definition at line 181 of file StimPlugin.h.
Referenced by getFpsMin(), and start().
double StimPlugin::fpsMax [protected]
Definition at line 181 of file StimPlugin.h.
Referenced by getFpsMax(), and start().
double StimPlugin::cycleTimeLeft [protected]
the number of seconds left in this cycle -- updated by glWindow before calling afterVSync
Definition at line 182 of file StimPlugin.h.
Referenced by CheckerFlicker::afterVSync(), getFrameDump(), and GLWindow::paintGL().
bool StimPlugin::needNotifyStart [protected]
iff true, we will notify LeoDAQGL of plugin start on unpause
Definition at line 183 of file StimPlugin.h.
Referenced by notifySpikeGLAboutStart(), notifySpikeGLAboutStop(), GLWindow::pauseUnpause(), start(), and StimPlugin().
QMutex StimPlugin::mut [mutable, protected]
plugin-level mutex -- used in a couple of functions and you may reuse it yourself as well
Definition at line 189 of file StimPlugin.h.
Referenced by getParam(), getParams(), and setParams().
std::vector<unsigned> StimPlugin::missedFrames [protected]
a list of skipped/missed frames -- the id number is in relative frame # or frameNum (as opposed to abs frame # which is what getHWFrameCount() would return)
Definition at line 194 of file StimPlugin.h.
Referenced by getNumMissedFrames(), putMissedFrame(), and start().
std::vector<unsigned> StimPlugin::missedFrameTimes [protected]
a list of cycle times for skipped/missed frames, in msecs
Definition at line 196 of file StimPlugin.h.
Referenced by putMissedFrame(), and start().
RNG StimPlugin::ran1Gen [protected]
Generic random number generator provided here as a convenience.
This generator is of type RNG::Ran1 and as such is similar to the ran1() function specified in Numerical Recipes.
Definition at line 202 of file StimPlugin.h.
Referenced by MovingObjects::drawFrame(), CalibPlugin::drawFrame(), MovingObjects::init(), and CheckerFlicker::init().
RNG StimPlugin::gasGen [protected]
Generic gaussian random number generator provided here as a convenience.
This generator is of type RNG::Gasdev and as such is similar to the gasdev() function specified in Numerical Recipes.
Definition at line 202 of file StimPlugin.h.
Referenced by CheckerFlicker::init().
RNG StimPlugin::ran0Gen [protected]
Generic random number generator provided here as a convenience.
This generator is of type RNG::Ran0 and as such is similar to the ran0() function specified in Numerical Recipes.
Definition at line 202 of file StimPlugin.h.
QString StimPlugin::customStatusBarString [protected]
Write to this variable to optionally inform the application that you want a custom message printed to the status bar.
Update this periodically to have the ConsoleWindow status bar include additional plugin-specific information -- may or may not appear right away typically the status bar is refreshed every 250ms by StimApp.cpp
Definition at line 221 of file StimPlugin.h.
Referenced by CheckerFlicker::afterVSync(), getSBString(), and start().
QTextStream StimPlugin::outStream [protected]
the output stream you should use in your "save()" method reimplementation -- already opened for you if your save() method is being called
Definition at line 224 of file StimPlugin.h.
Referenced by CheckerFlicker::save().
QFile StimPlugin::outFile [protected]
Write to this file when saving data.
Definition at line 226 of file StimPlugin.h.
Referenced by saveData().
QDateTime StimPlugin::begintime [protected]
used to indicate when start() and stop() were called for this plugin, used by writeGeneralInfo() as an FYI for the log data file
Definition at line 232 of file StimPlugin.h.
Referenced by getBeginTime(), and start().
QDateTime StimPlugin::endtime [protected]
Definition at line 232 of file StimPlugin.h.
Referenced by start(), and stop().
The documentation for this class was generated from the following files:
StimPlugin.h
StimPlugin.cpp