StimulateOpenGL_II: GridPlugin Class Reference
GridPlugin Class Reference
Abstract class for plugins wishing to have access to a 'grid' for drawing.
#include <GridPlugin.h>
Public Member Functions
virtual void stop ()
reimplementation deletes the grid data
Protected Member Functions
GridPlugin (const QString &name)
virtual ~GridPlugin ()
void setupGrid (int low, int left, int xWidth, int yWidth, int xNumber, int yNumber)
Define the grid and setup its data structures.
void drawGrid ()
Renders the grid to the screen using a glDrawArrays command.
void setGrayLevel (int x, int y, float intensity)
Sets the gray level of a single grid rectangle at row y col x to intensity.
void setColor (int x, int y, float r, float g, float b)
Set the color of a single grid rectangle at row y col x to have color compontents r,g,b.
Detailed Description
Abstract class for plugins wishing to have access to a 'grid' for drawing.
An abstract class that implements the 'grid' which is a 2d array of rectangles. Subclasses have access to the setupGrid() and drawGrid() methods, along with the setGrayLevel() and setColor() methods. See the MovingGrating class for a class that uses the 'grid'.
Definition at line 11 of file GridPlugin.h.
Constructor & Destructor Documentation
GridPlugin::GridPlugin (const QString & name) [protected]
Definition at line 3 of file GridPlugin.cpp.
GridPlugin::~GridPlugin () [protected, virtual]
Definition at line 7 of file GridPlugin.cpp.
Member Function Documentation
void GridPlugin::setupGrid (int low, int left, int xWidth, int yWidth, int xNumber, int yNumber) [protected]
Define the grid and setup its data structures.
Call this before you can call setGrayLevel(), setColor(), or drawGrid(). This method sets up the vertex arrays and color array defining the grid rectangles.
Parameters:
low - the y coordinate of the bottom of the grid
left - the x coordinate of the leftmost part of the grid
xWidth - the width in pixels of the grid along the x dimension
yWidth - the height in pixels of the grid along the y dimension
xNumber - the number of grid rectangles in the x direction. xWidth/xNumber determines the width of each grid rectangle.
yNumber - the number of grid rectangles in the y direction. yWidth/yNumber determines the height of each grid rectangle
Definition at line 32 of file GridPlugin.cpp.
Referenced by MovingGrating::init().
void GridPlugin::drawGrid () [protected]
Renders the grid to the screen using a glDrawArrays command.
Definition at line 77 of file GridPlugin.cpp.
Referenced by MovingGrating::drawFrame().
void GridPlugin::setGrayLevel (int x, int y, float intensity) [inline, protected]
Sets the gray level of a single grid rectangle at row y col x to intensity.
Definition at line 33 of file GridPlugin.h.
Referenced by MovingGrating::drawFrame().
void GridPlugin::setColor (int x, int y, float r, float g, float b) [inline, protected]
Set the color of a single grid rectangle at row y col x to have color compontents r,g,b.
Definition at line 35 of file GridPlugin.h.
void GridPlugin::stop () [virtual]
reimplementation deletes the grid data
Definition at line 9 of file GridPlugin.cpp.
References StimPlugin::stop().
The documentation for this class was generated from the following files:
GridPlugin.h
GridPlugin.cpp